### ISSUE TITLE
Why choose integrity business services section : title layout is not implemented as per the prototype at resolutions 320, 360

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Integrity-Business-Services#20]
Browsers : Mozilla39, Chrome43, Opera30, IE9, Safari
Devices : Itouch, Samsung S4

![why_choose_e7_it](https://cloud.githubusercontent.com/assets/13309806/9084031/dc0583ee-3b1b-11e5-84f1-f269dc1a14a6.png)
![why_choose_ibs_layout_ 320 640all](https://cloud.githubusercontent.com/assets/13309806/9084042/f795dc12-3b1b-11e5-8b74-32492d2bdecd.png)

**Comment by saif-titan** [comment]
Title layout is depend on the text.
