### ISSUE TITLE
Admin : Lead-in is still displaying when featured image is removed in admin panel 

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Integrity-Business-Services#35]
![lead-ins01](https://cloud.githubusercontent.com/assets/13309806/9105219/2a4bcae4-3bc2-11e5-9f2d-94b07cbc4d54.png)

**Comment by saif-titan** [comment]
Lead-in icons are pulled from ACF with names icon normal and icon hover

**Comment by ravi-josyula** [comment]
It is specified in the project scope to use Featured image. Please confirm with your TL.

![scopes](https://cloud.githubusercontent.com/assets/13309806/9327840/78085c94-45c1-11e5-949e-bac50255e5ae.png)

**Comment by saif-titan** [comment]
Scope has been reviced. please review
