### ISSUE TITLE
Accounting software page : Comment input field width should be 848px, but currently used is 830px

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Integrity-Business-Services#40]
![w-830 h-108](https://cloud.githubusercontent.com/assets/13309806/9105564/666855b2-3bc5-11e5-8008-23099572de75.png)

**Comment by saif-titan** [comment]
Not a bug, discussed the same with the TL as it's occupying the entire container and matching up with the GUI properly. So no need to change it's size.
